using Client.Wpf.Presenters.Interfaces;
using Client.Wpf.Windows.Interfaces;
using Core.Helpers.Logger.Interfaces;
using System.Windows;

namespace Client.Wpf.Windows
{
    public class BaseWindow : Window, IBaseWindow
    {
        #region Properties

        /// <summary> An instance of an active logger. </summary>
        public IActiveLogger Log { get; }

        public IPresenter Presenter { get; private set; }

        #endregion Properties
        #region Constructors

        /// <summary> Creates a new window. </summary>
        /// <param name="logCategory"> The category of logs generated by this instance. </param>
        /// <param name="parentWindow"> The window that owns this one. </param>
        /// <param name="presenter"> The presenter to attach. </param>
        public BaseWindow(string logCategory, IBaseWindow parentWindow, IPresenter presenter)
        {
            Log = ApplicationHelpers.CreateActiveLogger(logCategory);
            Owner = parentWindow as Window;

            Presenter = presenter;
            Presenter.SetParentWindow(this);
        }

        #endregion Constructors

        /// <summary> Applies localization to visible text in the window. </summary>
        public virtual void Localize()
        {
        }

        /// <summary> Removes references to instances on adjacent levels. </summary>
        public void Dispose()
        {
            Presenter = null;
        }
    }
}